### ISSUE TITLE
Resolve the error of redirecting.

### ISSUE THREAD

**Issue by deep1296** [prateek-bka/lazy-hose-3359#34]
- [x] On click any link from the navbar error is there.
<img width="539" alt="Screenshot 2023-04-06 174919" src="https://user-images.githubusercontent.com/96063026/230377104-a9bbef75-d208-4334-8ff0-92b04f123774.png">

- [x] On refreshing the page same error is there

**Comment by Sameerpadhy50** [comment]
Resolved and Reviewed
